services:
  web:
    build: .
    image: example
    ports:
      - '1337'
    environment:
      - NODE_ENV=docker
    restart: always

  db:
    image: postgres
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5555:5432'
    environment:
      PGUSER: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres_password'

volumes:
  postgresqldata: